services:
  - type: web
    name: car-rental
    env: php
    buildCommand: composer install --no-interaction --no-dev --prefer-dist
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: PHP_VERSION
        value: 8.1
    healthCheckPath: /
